//
//  PlanViewController.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 18/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PlanViewController: UIViewController {

    // MARK: - Private properties -
    
    // MARK: - Public properties -
    
    var presenter: PlanPresenterInterface!

    // MARK: - IBOutlets -
    
    @IBOutlet weak var tableView: UITableView!
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
        
        _configureUI()
    }

    // MARK: - IBActions -
    
    @IBAction func didTapSavePlanButton(_ sender: UIButton) {
        
    }

    // MARK: - Private functions -
    
    fileprivate func _configureUI() {
        navigationController?.navigationBar.tintColor = UIColor.white
        navigationItem.title = "Novi plan"
    }
}

// MARK: - Extensions -

extension PlanViewController: PlanViewInterface {
}

extension PlanViewController: UITableViewDelegate, UITableViewDataSource {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return presenter.numberOfSections()
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter.numberOfItems(in: section)
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let item = presenter.item(for: indexPath)
        let cellIdentifier: String
        
        switch item {
        case .dateItem(let item):
            cellIdentifier = Constants.ReuseIdentifiers.TableViewCells.PlanDateCell
            let cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier, for: indexPath) as! PlanDateCell
            cell.configure(with: item)
            cell.delegate = self
            return cell
        case .locationItem(let item):
            cellIdentifier = Constants.ReuseIdentifiers.TableViewCells.PlanLocationCell
            let cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier, for: indexPath) as! PlanLocationCell
            cell.configure(with: item)
            cell.locations = presenter.locations()
            return cell
        case .forecastItem(let item):
            cellIdentifier = Constants.ReuseIdentifiers.TableViewCells.PlanForecastCell
            let cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier, for: indexPath) as! PlanForecastCell
            cell.configure(with: item)
            return cell
        case .galleryItem:
            cellIdentifier = Constants.ReuseIdentifiers.TableViewCells.PlanGalleryCell
            let cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier, for: indexPath) as! PlanGalleryCell
            return cell
        }
    }
    
    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return section == 0 ? 44.0 : 0.001
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        let item = presenter.item(for: indexPath)
        
        switch item {
        case .dateItem:
            return 142.0
        case .locationItem:
            return 95.0
        case .forecastItem:
            return 121.0
        case .galleryItem:
            return 153.0
        }
    }
    
    func tableView(_ tableView: UITableView, shouldHighlightRowAt indexPath: IndexPath) -> Bool {
        return false
    }
    
}

extension PlanViewController: PlanDateCellDelegate {
    
    func didSet(startDate: Date, endDate: Date) {
        print("Start date: \(startDate) - End date: \(endDate)")
    }
    
}
