//
//  PlanInteractor.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 18/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PlanInteractor: NSObject {

    // MARK: - Private functions -
    
}

// MARK: - Extensions -

extension PlanInteractor: PlanInteractorInterface {
    
    func loadLocations() -> [String]? {
        return UserDefaults.standard.stringArray(forKey: Constants.UserDefaultsKeys.FavoriteLocations)
    }
    
}
