//
//  TabBarPresenter.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 14/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TabBarPresenter: NSObject {
    
    // MARK: - Private properties -

    fileprivate weak var _view: TabBarViewInterface?
    fileprivate var _interactor: TabBarInteractorInterface
    fileprivate var _wireframe: TabBarWireframeInterface
    
    // MARK: - Lifecycle -
    
    init (wireframe: TabBarWireframeInterface, view: TabBarViewInterface, interactor: TabBarInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }

    // MARK: - Private functions -
    
}

// MARK: - Extensions -

extension TabBarPresenter: TabBarPresenterInterface {
    
    func didSelectNavigationAction(action: TabBarNavigationAction) {
        _wireframe.performNavigationAction(action: action)
    }
    
}
