//
//  TabBarViewController.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 14/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TabBarViewController: UITabBarController {

    // MARK: - Private properties -
    
    // MARK: - Public properties -
    
    var presenter: TabBarPresenterInterface!

    // MARK: - IBOutlets -
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.tabBar.tintColor = UIColor.appLightBlue()
    }

    // MARK: - IBActions -

    // MARK: - Private functions -
    
    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
}

// MARK: - Extensions -

extension TabBarViewController: TabBarViewInterface {
}
