//
//  LocationsWireframe.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 22/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

struct LocationsContext {
}

final class LocationsWireframe: NSObject {
    
    // MARK: - Private properties -

    private var _context: LocationsContext?
    private let _storyboard: UIStoryboard = UIStoryboard(name: Constants.StoryboardIdentifiers.Locations, bundle: nil)
    
    // MARK: - Public properties -
    
    weak var navigationController: UINavigationController?
    weak var viewController: UIViewController?
    
    // MARK: - Lifecycle -
    
    init(navigationController: UINavigationController? = nil, context: LocationsContext? = nil) {
        super.init()
        _context = context
        self.navigationController = navigationController
    }
    
    // MARK: - Module setup -
    
    func instantiateAndConfigureModule() -> UIViewController {
        guard let viewController = _storyboard.instantiateViewController(withIdentifier: Constants.ViewControllerIdentifiers.Locations) as? LocationsViewController else {
            fatalError("No view controller found with the following identifier: \(Constants.ViewControllerIdentifiers.Locations)")
        }
        
        configureModuleWithViewController(viewController: viewController)
        
        return viewController
    }
    
    func configureModuleWithViewController(viewController: LocationsViewController) {
        let interactor = LocationsInteractor()
        let presenter = LocationsPresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
        self.viewController = viewController
    }

}

// MARK: - Extensions -

extension LocationsWireframe: LocationsWireframeInterface {
    
    func performNavigationAction(action: LocationsNavigationAction) {
        switch action {
        default:
            break
        }
    }

}
