//
//  LocationsPresenter.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 22/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LocationsPresenter: NSObject {
    
    // MARK: - Private properties -

    fileprivate weak var _view: LocationsViewInterface?
    fileprivate var _interactor: LocationsInteractorInterface
    fileprivate var _wireframe: LocationsWireframeInterface
    
    // MARK: - Lifecycle -
    
    init (wireframe: LocationsWireframeInterface, view: LocationsViewInterface, interactor: LocationsInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }

    // MARK: - Private functions -
    
}

// MARK: - Extensions -

extension LocationsPresenter: LocationsPresenterInterface {
    
    func didSelectNavigationAction(action: LocationsNavigationAction) {
        _wireframe.performNavigationAction(action: action)
    }
    
}
