//
//  LocationsInteractor.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 22/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class LocationsInteractor: NSObject {

    // MARK: - Private functions -
    
}

// MARK: - Extensions -

extension LocationsInteractor: LocationsInteractorInterface {
}
