//
//  HomeInteractor.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 14/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomeInteractor: NSObject {

    // MARK: - Private functions -
    
}

// MARK: - Extensions -

extension HomeInteractor: HomeInteractorInterface {
    
    func loadPlans() -> [ExtraPlanInfoItem] {
        guard let savedPlanData = UserDefaults.standard.object(forKey: Constants.UserDefaultsKeys.SavedPlans) as? [String] else {
            return []
        }
        
        var plans = [ExtraPlanInfoItem]()
        
        for item in savedPlanData {
            let decodedPlan = item.components(separatedBy: "-")
            let ID = decodedPlan[0]
            let location = decodedPlan[1]
            let dateFrom = DateFormatter.shared.date(from: decodedPlan[2], withFormat: DateFormat.defaultFormat)!
            let dateTo = DateFormatter.shared.date(from: decodedPlan[3], withFormat: DateFormat.defaultFormat)!
            
            let plan = ExtraPlanInfoItem(ID: ID, location: location, dateFrom: dateFrom, dateTo: dateTo)
            
            plans.append(plan)
        }
        
        return plans
    }
    
    func save(plans: [ExtraPlanInfoItem]) {
        var encodedPlans = [String]()
        
        for plan in plans {
            encodedPlans.append(plan.encodedPlanData())
        }
        
        UserDefaults.standard.set(encodedPlans, forKey: Constants.UserDefaultsKeys.SavedPlans)
    }
    
}
