//
//  HomeViewController.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 14/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeViewController: UIViewController {

    // MARK: - Private properties -
    
    // MARK: - Public properties -
    
    var presenter: HomePresenterInterface!

    // MARK: - IBOutlets -
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }

    // MARK: - IBActions -

    // MARK: - Private functions -
}

// MARK: - Extensions -

extension HomeViewController: HomeViewInterface {
}

extension HomeViewController: TabBarItemConfigurable {
    func tabBarItemTitle() -> String {
        return "Planovi"
    }
    
    func tabBarItemDeselectedImageName() -> String {
        return "ic_home"
    }
    
    func tabBarItemSelectedImageName() -> String {
        return "ic_home"
    }
}
