//
//  LoginViewController.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 17/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginViewController: UIViewController {

    // MARK: - Private properties -
    
    // MARK: - Public properties -
    
    var presenter: LoginPresenterInterface!

    // MARK: - IBOutlets -
    
    @IBOutlet weak var signInButtonContainerView: UIView!
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }

    // MARK: - IBActions -

    // MARK: - Private functions -
}

// MARK: - Extensions -

extension LoginViewController: LoginViewInterface {
}
