//
//  LoginWireframe.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 17/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

struct LoginContext {
}

final class LoginWireframe: NSObject {
    
    // MARK: - Private properties -

    private var _context: LoginContext?
    private let _storyboard: UIStoryboard = UIStoryboard(name: Constants.StoryboardIdentifiers.Login, bundle: nil)
    
    // MARK: - Public properties -
    
    weak var navigationController: UINavigationController?
    weak var viewController: UIViewController?
    
    // MARK: - Lifecycle -
    
    init(navigationController: UINavigationController? = nil, context: LoginContext? = nil) {
        super.init()
        _context = context
        self.navigationController = navigationController
    }
    
    // MARK: - Module setup -
    
    func instantiateAndConfigureModule() -> UIViewController {
        guard let viewController = _storyboard.instantiateViewController(withIdentifier: Constants.ViewControllerIdentifiers.Login) as? LoginViewController else {
            fatalError("No view controller found with the following identifier: \(Constants.ViewControllerIdentifiers.Login)")
        }
        
        configureModuleWithViewController(viewController: viewController)
        
        return viewController
    }
    
    func configureModuleWithViewController(viewController: LoginViewController) {
        let interactor = LoginInteractor()
        let presenter = LoginPresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
        self.viewController = viewController
    }

}

// MARK: - Extensions -

extension LoginWireframe: LoginWireframeInterface {
    
    func performNavigationAction(action: LoginNavigationAction) {
        switch action {
        case .didSignIn:
            guard let window = UIApplication.shared.windows.first else {
                return
            }
            
            UIView.transition(with: window, duration: 0.6, options: .transitionFlipFromLeft, animations: {
                window.rootViewController = TabBarWireframe().instantiateAndConfigureModule()
            }, completion: nil)
        }
    }

}
