//
//  LoginPresenter.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 17/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginPresenter: NSObject {
    
    // MARK: - Private properties -

    fileprivate weak var _view: LoginViewInterface?
    fileprivate var _interactor: LoginInteractorInterface
    fileprivate var _wireframe: LoginWireframeInterface
    
    // MARK: - Lifecycle -
    
    init (wireframe: LoginWireframeInterface, view: LoginViewInterface, interactor: LoginInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }

    // MARK: - Private functions -
    
}

// MARK: - Extensions -

extension LoginPresenter: LoginPresenterInterface {
    
    func didSelectNavigationAction(action: LoginNavigationAction) {
        _wireframe.performNavigationAction(action: action)
    }
    
}
