//
//  LoginInterfaces.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 17/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

// MARK: - Navigation -

enum LoginNavigationAction {
}

// MARK: - Login Wireframe Interface -

protocol LoginWireframeInterface: WireframeInterface {
    func performNavigationAction(action: LoginNavigationAction)
    func configureModuleWithViewController(viewController: LoginViewController)
}

// MARK: - Login View Interface -

protocol LoginViewInterface: ViewInterface {
}

// MARK: - Login Presenter Interface -

protocol LoginPresenterInterface: PresenterInterface {
    func didSelectNavigationAction(action: LoginNavigationAction)
}

// MARK: - Login Interactor Interface -

protocol LoginInteractorInterface: InteractorInterface {
}
