//
//  LoginViewController.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 17/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Google
import GTMOAuth2
import GoogleSignIn
import GoogleAPIClientForREST

final class LoginViewController: UIViewController {

    // MARK: - Private properties -
    
    fileprivate let _scopes = [kGTLRAuthScopeCalendar]
    fileprivate let _service = GTLRCalendarService()
    fileprivate let _signInButton = GIDSignInButton()
    
    // MARK: - Public properties -
    
    var presenter: LoginPresenterInterface!

    // MARK: - IBOutlets -
    
    @IBOutlet weak var signInButtonContainerView: UIView!
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Configure Google Sign-in.
        GIDSignIn.sharedInstance().clientID = "41958465849-c7lkntnc6g5888nbvs5csjr1rvreetn1.apps.googleusercontent.com"
        GIDSignIn.sharedInstance().delegate = self
        GIDSignIn.sharedInstance().uiDelegate = self
        GIDSignIn.sharedInstance().scopes = _scopes
        GIDSignIn.sharedInstance().signInSilently()
        
        signInButtonContainerView.addSubview(_signInButton)
        _signInButton.center = signInButtonContainerView.convert(signInButtonContainerView.center, from: signInButtonContainerView.superview)
    }

    // MARK: - IBActions -

    // MARK: - Private functions -
}

// MARK: - Extensions -

extension LoginViewController: LoginViewInterface {
}

extension LoginViewController: GIDSignInDelegate {
    
    func sign(_ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!, withError error: Error!) {
        if let error = error {
            self._service.authorizer = nil
            GoogleService.shared.gService = nil
            presenter.didFailToSignIn(withError: error)
        } else {
            _service.authorizer = user.authentication.fetcherAuthorizer()
            _service.apiKey = "AIzaSyBDiIW_pV4mPI9JxiSeK3LWgyYODOqlL9k"
            GoogleService.shared.gService = _service
            presenter.didSignIn()
        }
    }
    
}

extension LoginViewController: GIDSignInUIDelegate {
    
    
}
