//
//  FavoritesInterfaces.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 14/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

// MARK: - Navigation -

enum FavoritesNavigationAction {
}

// MARK: - Favorites Wireframe Interface -

protocol FavoritesWireframeInterface: WireframeInterface {
    func performNavigationAction(action: FavoritesNavigationAction)
    func configureModuleWithViewController(viewController: FavoritesViewController)
}

// MARK: - Favorites View Interface -

protocol FavoritesViewInterface: ViewInterface {
}

// MARK: - Favorites Presenter Interface -

protocol FavoritesPresenterInterface: PresenterInterface {
    func didSelectNavigationAction(action: FavoritesNavigationAction)
}

// MARK: - Favorites Interactor Interface -

protocol FavoritesInteractorInterface: InteractorInterface {
}
