//
//  FavoritesInterfaces.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 14/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

// MARK: - Navigation -

enum FavoritesNavigationAction {
    case newLocation
}

// MARK: - Favorites Wireframe Interface -

protocol FavoritesWireframeInterface: WireframeInterface {
    func performNavigationAction(action: FavoritesNavigationAction)
    func configureModuleWithViewController(viewController: FavoritesViewController)
}

// MARK: - Favorites View Interface -

protocol FavoritesViewInterface: ViewInterface {
    func reloadData()
}

// MARK: - Favorites Presenter Interface -

protocol FavoritesPresenterInterface: PresenterInterface {
    func didSelectNavigationAction(action: FavoritesNavigationAction)
    
    func numberOfSections() -> Int
    func numberOfRows(in section: Int) -> Int
    func didSelectItem(at indexPath: IndexPath)
    func didDeleteItem(at indexPath: IndexPath)
    func item(at indexPath: IndexPath) -> LocationItem
}

// MARK: - Favorites Interactor Interface -

protocol FavoritesInteractorInterface: InteractorInterface {
    func loadLocations() -> [String]?
    func storeLocations(_ locations: [String])
}
