//
//  FavoritesInteractor.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 14/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FavoritesInteractor: NSObject {

    // MARK: - Private functions -
    
}

// MARK: - Extensions -

extension FavoritesInteractor: FavoritesInteractorInterface {
    
    func loadLocations() -> [String]? {
        return UserDefaults.standard.stringArray(forKey: Constants.UserDefaultsKeys.FavoriteLocations)
    }
    
    func storeLocations(_ locations: [String]) {
        UserDefaults.standard.set(locations, forKey: Constants.UserDefaultsKeys.FavoriteLocations)
    }
    
}
