//
//  FavoritesWireframe.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 14/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

struct FavoritesContext {
}

final class FavoritesWireframe: NSObject {
    
    // MARK: - Private properties -

    private var _context: FavoritesContext?
    private let _storyboard: UIStoryboard = UIStoryboard(name: Constants.StoryboardIdentifiers.Favorites, bundle: nil)
    
    // MARK: - Public properties -
    
    weak var navigationController: UINavigationController?
    weak var viewController: UIViewController?
    
    // MARK: - Lifecycle -
    
    init(navigationController: UINavigationController? = nil, context: FavoritesContext? = nil) {
        super.init()
        _context = context
        self.navigationController = navigationController
    }
    
    // MARK: - Module setup -
    
    func instantiateAndConfigureModule() -> UIViewController {
        guard let viewController = _storyboard.instantiateViewController(withIdentifier: Constants.ViewControllerIdentifiers.Favorites) as? FavoritesViewController else {
            fatalError("No view controller found with the following identifier: \(Constants.ViewControllerIdentifiers.Favorites)")
        }
        
        configureModuleWithViewController(viewController: viewController)
        viewController.configureTabBarItem()
        
        return viewController
    }
    
    func configureModuleWithViewController(viewController: FavoritesViewController) {
        let interactor = FavoritesInteractor()
        let presenter = FavoritesPresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
        self.viewController = viewController
    }

}

// MARK: - Extensions -

extension FavoritesWireframe: FavoritesWireframeInterface {
    
    func performNavigationAction(action: FavoritesNavigationAction) {
        switch action {
        case .newLocation:
            let wireframe = LocationsWireframe()
            let viewController = wireframe.instantiateAndConfigureModule()
            navigationController?.pushViewController(viewController, animated: true)
        }
    }

}
