//
//  SettingsPresenter.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 14/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SettingsPresenter: NSObject {
    
    // MARK: - Private properties -

    fileprivate weak var _view: SettingsViewInterface?
    fileprivate var _interactor: SettingsInteractorInterface
    fileprivate var _wireframe: SettingsWireframeInterface
    
    // MARK: - Lifecycle -
    
    init (wireframe: SettingsWireframeInterface, view: SettingsViewInterface, interactor: SettingsInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }

    // MARK: - Private functions -
    
}

// MARK: - Extensions -

extension SettingsPresenter: SettingsPresenterInterface {
    
    func didSelectNavigationAction(action: SettingsNavigationAction) {
        _wireframe.performNavigationAction(action: action)
    }
    
}
