//
//  SettingsInterfaces.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 14/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

// MARK: - Navigation -

enum SettingsNavigationAction {
}

// MARK: - Settings Wireframe Interface -

protocol SettingsWireframeInterface: WireframeInterface {
    func performNavigationAction(action: SettingsNavigationAction)
    func configureModuleWithViewController(viewController: SettingsViewController)
}

// MARK: - Settings View Interface -

protocol SettingsViewInterface: ViewInterface {
}

// MARK: - Settings Presenter Interface -

protocol SettingsPresenterInterface: PresenterInterface {
    func didSelectNavigationAction(action: SettingsNavigationAction)
}

// MARK: - Settings Interactor Interface -

protocol SettingsInteractorInterface: InteractorInterface {
}
