//
//  SettingsInteractor.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 14/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class SettingsInteractor: NSObject {

    // MARK: - Private functions -
    
}

// MARK: - Extensions -

extension SettingsInteractor: SettingsInteractorInterface {
}
