//
//  SettingsViewController.swift
//  TravelPlaner
//
//  Created by Nikola Simunko on 14/08/2017.
//  Copyright (c) 2017 Nikola Simunko. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SettingsViewController: UIViewController {

    // MARK: - Private properties -
    
    // MARK: - Public properties -
    
    var presenter: SettingsPresenterInterface!

    // MARK: - IBOutlets -
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }

    // MARK: - IBActions -

    // MARK: - Private functions -
}

// MARK: - Extensions -

extension SettingsViewController: SettingsViewInterface {
}
